#!/usr/sbin/nft -f

flush ruleset

table ip nat {
    chain postrouting {
        type nat hook postrouting priority 100;
        oifname "enp1s0" ip saddr 192.168.10.0/24 masquerade
    }
}

table inet filter {
    chain forward {
        type filter hook forward priority 0; policy drop;
        iifname "enp3s0" oifname "enp1s0" accept
        iifname "enp1s0" oifname "enp3s0" ct state established,related accept
    }
    chain input {
        type filter hook input priority 0; policy drop;
        iifname "lo" accept
        ct state established,related accept
        ct state invalid drop
        iifname "enp3s0" udp dport { 67, 68 } accept   # DHCP
        iifname "enp3s0" tcp dport 22 accept            # SSH des de LAN, per exemple
        ip protocol icmp accept
    }
}
