#!/usr/sbin/nft -f
# esborrany en proves
flush ruleset

table ip nat {
    chain postrouting {
        type nat hook postrouting priority 100;
        oifname "enp1s0" ip saddr  { 192.168.10.0/24, 192.168.12.0/24 } masquerade
    }

    chain prerouting {
        type nat hook prerouting priority -100;
        
        # Port forwarding to DMZ
        iifname "enp1s0" tcp dport 80 dnat to 192.168.12.2:80
        iifname "enp1s0" tcp dport 443 dnat to 192.168.12.2:443
    }
}

table inet filter {
    chain forward {
        type filter hook forward priority 0; policy drop;
        ct state invalid drop
        # accés des de internet a la DMZ
        iifname "enp1s0" oifname "enp4s0" tcp dport { 80, 443 } accept 

        # accés des de la DMZ a internet
        iifname "enp4s0" oifname "enp1s0" ct state established,related accept
        iifname "enp4s0" oifname "enp1s0" tcp dport { 53, 80, 443 } accept
        iifname "enp4s0" oifname "enp1s0" udp dport 53 accept
        # sortida a internet de la LAN
        iifname "enp3s0" oifname "enp1s0" accept
        iifname "enp1s0" oifname "enp3s0" ct state established,related accept
        # accés des de wireguard-vpn a la LAN
        iifname "enp2s0" oifname "enp3s0" accept
        iifname "enp3s0" oifname "enp2s0" ct state established,related accept

        icmp type { destination-unreachable, time-exceeded } accept
    }

    chain input {
        type filter hook input priority 0; policy drop;
        iifname "lo" accept
        ct state established,related accept
        ct state invalid drop
        iifname "enp3s0" udp dport { 67, 68 } accept   # DHCP
        iifname "enp3s0" tcp dport 22 accept            # SSH des de LAN, per exemple
        iifname "enp2s0" tcp dport 22 accept            # SSH des de Wireguard-VPN des de VSC, per exemple
        #ip protocol icmp accept
        icmp type echo-request limit rate 5/second accept
    }
}
